export type Role = 'admin' | 'player' | 'spectator';
export type AccountRole = 'admin' | 'player';

export interface AuthUser {
  username: string;
  role: AccountRole;
}

export interface AccountSummary extends AuthUser {
  createdAt: number;
}

export type RoundType = 'warmup' | 'obstacle' | 'acceleration' | 'finish' | 'summary';

export interface Player {
  id: string;
  name: string;
  avatar: string; // Emoji or preset avatar
  color: string;
  score: number;
  isReady: boolean;
  isOnline: boolean;
  buzzerTime?: number; // Milliseconds timestamp when buzzer was pressed
  lastAnswerResult?: {
    isCorrect: boolean;
    pointsAwarded: number;
    timestamp: number;
  };
}

export interface WarmUpQuestion {
  id: string;
  question: string;
  answer: string;
  choices?: string[];
  explanation?: string;
  targetPlayerId?: string; // Player 1 or Player 2 or shared
  points: number; // usually 10
}

export interface ObstacleClue {
  number: number;
  question: string;
  answer: string;
  choices?: string[];
  letterCount: number;
  isOpened: boolean;
  isAnswered?: boolean;
}

export interface ObstacleQuestion {
  keyword: string; // e.g., "QUANG TRUNG"
  keywordLength: number;
  hintDescription: string;
  clues: ObstacleClue[];
  keywordGuessedBy?: string; // playerId
  isKeywordRevealed: boolean;
}

export interface AccelerationQuestion {
  id: string;
  number: number;
  question: string;
  answer: string;
  choices?: string[];
  imageHint?: string; // Optional SVG/description or AI prompt image
  type: 'image' | 'text' | 'reorder' | 'logic';
}

export interface FinishQuestion {
  id: string;
  pointValue: 20 | 30; // 20 or 30 points
  question: string;
  answer: string;
  choices?: string[];
  explanation?: string;
}

export interface PlayerFinishPackage {
  playerId: string;
  questions: FinishQuestion[];
  currentQuestionIndex: number;
}

export interface OlympiaQuestions {
  warmup: WarmUpQuestion[];
  obstacle: ObstacleQuestion;
  acceleration: AccelerationQuestion[];
  finish: {
    player1Package: FinishQuestion[];
    player2Package: FinishQuestion[];
    player3Package?: FinishQuestion[];
    player4Package?: FinishQuestion[];
    [key: string]: FinishQuestion[] | undefined;
  };
}

export interface ActiveBuzzer {
  playerId: string;
  playerName: string;
  timestamp: number;
  round: RoundType;
  answer?: string;
}

export interface GameState {
  roomId: string;
  roomCode: string;
  hostPlayerId?: string;
  status: 'waiting' | 'ready' | 'playing' | 'ended';
  currentRound: RoundType;
  currentQuestionIndex: number;
  currentActivePlayerId?: string; // For Về Đích or Khởi Động turns
  
  // Players
  players: Player[]; // max 4
  
  // Timer
  timerSeconds: number;
  timerActive: boolean;

  // Questions generated by Gemini
  questions?: OlympiaQuestions;
  
  // Round-specific state
  warmupState?: {
    currentQuestionIndex: number;
    playerAnswers: Record<string, string>; // questionId -> answer
    attemptedPlayerIds: string[];
    phase: 'awaiting_buzzer' | 'answering' | 'revealing' | 'completed';
    revealedAnswer?: string;
    revealReason?: 'all_failed' | 'no_buzzer';
  };

  obstacleState?: {
    openedClues: number[]; // row numbers 1..4
    currentClueIndex?: number;
    keywordGuessed: boolean;
    keywordWinnerId?: string;
    keywordPointsAwarded?: number;
    selectionOrder: string[];
    selectionTurnIndex: number;
    phase: 'selecting_clue' | 'answering_clue' | 'keyword_answering' | 'final_keyword_window' | 'revealing_keyword' | 'completed';
    resumePhase?: 'selecting_clue' | 'answering_clue' | 'final_keyword_window' | 'completed';
    resumeTimerSeconds?: number;
    clueSubmissions: Array<{
      playerId: string;
      answer: string;
      isCorrect: boolean;
    }>;
    eliminatedPlayerIds: string[];
  };

  accelerationState?: {
    currentQuestionIndex: number;
    playerSubmissions: Array<{
      playerId: string;
      answer: string;
      timestamp: number;
      isCorrect?: boolean;
      pointsAwarded?: number;
    }>;
  };

  finishState?: {
    activeTurnPlayerId: string;
    questionIndex: number;
    starOfHopeActive: boolean;
    stealerPlayerId?: string;
    buzzerOpen: boolean;
    mainPlayerAnswer?: string;
    stealerAnswer?: string;
    turnPhase: 'selecting_package' | 'question_active' | 'main_answering' | 'stealer_buzzer' | 'stealer_answering' | 'judging' | 'completed';
  };

  // Buzzer lock
  activeBuzzer?: ActiveBuzzer;
  buzzerLocked: boolean;

  // Recent logs/notifications
  logs: Array<{
    id: string;
    time: string;
    message: string;
    type: 'info' | 'success' | 'warning' | 'buzzer';
  }>;
}

export type WSMessageType =
  | 'AUTH_LOGIN'
  | 'AUTH_RESTORE'
  | 'AUTH_LOGOUT'
  | 'AUTH_SUCCESS'
  | 'AUTH_ERROR'
  | 'LIST_ACCOUNTS'
  | 'CREATE_ACCOUNT'
  | 'DELETE_ACCOUNT'
  | 'ACCOUNT_LIST'
  | 'ACCOUNT_CREATED'
  | 'INIT_STATE'
  | 'STATE_UPDATE'
  | 'JOIN_ROOM'
  | 'REJOIN_ROOM'
  | 'CREATE_ROOM'
  | 'START_GAME'
  | 'GENERATE_QUESTIONS'
  | 'NEXT_ROUND'
  | 'PRESS_BUZZER'
  | 'SUBMIT_ANSWER'
  | 'JUDGE_ANSWER'
  | 'TOGGLE_STAR_OF_HOPE'
  | 'OPEN_OBSTACLE_CLUE'
  | 'SUBMIT_OBSTACLE_CLUE_ANSWER'
  | 'GUESS_OBSTACLE_KEYWORD'
  | 'UPDATE_SCORE'
  | 'TIMER_TICK'
  | 'START_TIMER'
  | 'PAUSE_TIMER'
  | 'RESET_GAME'
  | 'CANCEL_ROOM'
  | 'ROOM_CANCELLED'
  | 'ERROR';

export interface WSMessage {
  type: WSMessageType;
  roomId?: string;
  role?: Role;
  playerId?: string;
  authToken?: string;
  payload?: any;
}
